# This file is used by Figaro gem to load environment variables
# It now references variables from .env file (loaded by dotenv-rails)
# This maintains compatibility while using .env as the source of truth

development:
  SMTP_USERNAME: <%= ENV['SMTP_USERNAME'] %>
  SMTP_PASSWORD: <%= ENV['SMTP_PASSWORD'] %>
  FLIPPER_USERNAME: <%= ENV['FLIPPER_USERNAME'] %>
  FLIPPER_PASSWORD: <%= ENV['FLIPPER_PASSWORD'] %>
  BLOCKCHAIN_SERVER_URL: <%= ENV['BLOCKCHAIN_SERVER_URL'] %>
  PLAGSCAN_SERVER_URL: <%= ENV['PLAGSCAN_SERVER_URL'] %>
  PLAGSCAN_CLIENT_ID: <%= ENV['PLAGSCAN_CLIENT_ID'] %>
  PLAGSCAN_CLIENT_SECRET: <%= ENV['PLAGSCAN_CLIENT_SECRET'] %>
  STRIPE_SERVER_KEY: <%= ENV['STRIPE_SERVER_KEY'] %>
  ARTIZYOU_IMAGE_DOMAIN: <%= ENV['ARTIZYOU_IMAGE_DOMAIN'] %>
  AWS_REGION: <%= ENV['AWS_REGION'] %>
  AWS_ACCESS_KEY_ID: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  AWS_SECRET_ACCESS_KEY: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  AWS_BUCKET: <%= ENV['AWS_BUCKET'] %>
  FACEBOOK_KEY_ID: <%= ENV['FACEBOOK_KEY_ID'] %>
  FACEBOOK_SECRET_ACCESS_KEY: <%= ENV['FACEBOOK_SECRET_ACCESS_KEY'] %>
  GOOGLE_KEY_ID: <%= ENV['GOOGLE_KEY_ID'] %>
  GOOGLE_SECRET_ACCESS_KEY: <%= ENV['GOOGLE_SECRET_ACCESS_KEY'] %>
  GOOGLE_CALLBACK: <%= ENV['GOOGLE_CALLBACK'] %>
  LINKEDIN_KEY_ID: <%= ENV['LINKEDIN_KEY_ID'] %>
  LINKEDIN_SECRET_ACCESS_KEY: <%= ENV['LINKEDIN_SECRET_ACCESS_KEY'] %>
  APP_URL: <%= ENV['APP_URL'] %>
  PUBLIC_PROFILE_PATH: <%= ENV['PUBLIC_PROFILE_PATH'] %>
  SITE_URL: <%= ENV['SITE_URL'] %>
  FAQ_PATH: <%= ENV['FAQ_PATH'] %>
  EMAIL_FROM: <%= ENV['EMAIL_FROM'] %>
  ARTIZYOU_API_TOKEN: <%= ENV['ARTIZYOU_API_TOKEN'] %>
  ARTIZYOU_API_URL: <%= ENV['ARTIZYOU_API_URL'] %>

test:
  SMTP_USERNAME: <%= ENV['SMTP_USERNAME'] %>
  SMTP_PASSWORD: <%= ENV['SMTP_PASSWORD'] %>
  BLOCKCHAIN_SERVER_URL: <%= ENV['BLOCKCHAIN_SERVER_URL'] %>
  PLAGSCAN_SERVER_URL: <%= ENV['PLAGSCAN_SERVER_URL'] %>
  PLAGSCAN_CLIENT_ID: <%= ENV['PLAGSCAN_CLIENT_ID'] %>
  PLAGSCAN_CLIENT_SECRET: <%= ENV['PLAGSCAN_CLIENT_SECRET'] %>
  STRIPE_SERVER_KEY: <%= ENV['STRIPE_SERVER_KEY'] %>
  ARTIZYOU_IMAGE_DOMAIN: <%= ENV['ARTIZYOU_IMAGE_DOMAIN'] %>
  AWS_REGION: <%= ENV['AWS_REGION'] %>
  AWS_ACCESS_KEY_ID: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  AWS_SECRET_ACCESS_KEY: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  AWS_BUCKET: <%= ENV['AWS_BUCKET'] %>

production:
  SMTP_USERNAME: <%= ENV['SMTP_USERNAME'] %>
  SMTP_PASSWORD: <%= ENV['SMTP_PASSWORD'] %>
  FLIPPER_USERNAME: <%= ENV['FLIPPER_USERNAME'] %>
  FLIPPER_PASSWORD: <%= ENV['FLIPPER_PASSWORD'] %>
  BLOCKCHAIN_SERVER_URL: <%= ENV['BLOCKCHAIN_SERVER_URL'] %>
  PLAGSCAN_SERVER_URL: <%= ENV['PLAGSCAN_SERVER_URL'] %>
  PLAGSCAN_CLIENT_ID: <%= ENV['PLAGSCAN_CLIENT_ID'] %>
  PLAGSCAN_CLIENT_SECRET: <%= ENV['PLAGSCAN_CLIENT_SECRET'] %>
  STRIPE_SERVER_KEY: <%= ENV['STRIPE_SERVER_KEY'] %>
  ARTIZYOU_IMAGE_DOMAIN: <%= ENV['ARTIZYOU_IMAGE_DOMAIN'] %>
  AWS_REGION: <%= ENV['AWS_REGION'] %>
  AWS_ACCESS_KEY_ID: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  AWS_SECRET_ACCESS_KEY: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  AWS_BUCKET: <%= ENV['AWS_BUCKET'] %>
  FACEBOOK_KEY_ID: <%= ENV['FACEBOOK_KEY_ID'] %>
  FACEBOOK_SECRET_ACCESS_KEY: <%= ENV['FACEBOOK_SECRET_ACCESS_KEY'] %>
  GOOGLE_KEY_ID: <%= ENV['GOOGLE_KEY_ID'] %>
  GOOGLE_SECRET_ACCESS_KEY: <%= ENV['GOOGLE_SECRET_ACCESS_KEY'] %>
  GOOGLE_CALLBACK: <%= ENV['GOOGLE_CALLBACK'] %>
  LINKEDIN_KEY_ID: <%= ENV['LINKEDIN_KEY_ID'] %>
  LINKEDIN_SECRET_ACCESS_KEY: <%= ENV['LINKEDIN_SECRET_ACCESS_KEY'] %>
  APP_URL: <%= ENV['APP_URL'] %>
  PUBLIC_PROFILE_PATH: <%= ENV['PUBLIC_PROFILE_PATH'] %>
  SITE_URL: <%= ENV['SITE_URL'] %>
  FAQ_PATH: <%= ENV['FAQ_PATH'] %>
  EMAIL_FROM: <%= ENV['EMAIL_FROM'] %>
  ARTIZYOU_API_TOKEN: <%= ENV['ARTIZYOU_API_TOKEN'] %>
  ARTIZYOU_API_URL: <%= ENV['ARTIZYOU_API_URL'] %>
